name: Run FINRA OTC Scraper

on:
  schedule:
    - cron: '0 18 * * 1'  # Runs at 10 AM PST (6 PM UTC) every Monday
  workflow_dispatch:

jobs:
  run-finra-otc-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clean environment and upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y numpy pandas requests holidays || true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade numpy pandas requests holidays
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute FINRA OTC scraper script
        env:
          FINRA_CLIENT_ID: ${{ secrets.FINRA_CLIENT_ID }}
          FINRA_CLIENT_SECRET: ${{ secrets.FINRA_CLIENT_SECRET }}
        run: python scrape_logic/ats_scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add -f data_upload/ats_upload/filtered_weekly_otc_data_*.csv
          git commit -m "Update FINRA OTC weekly data CSV file [skip ci]" || echo "No changes to commit"
          git push --force
