name: Run fomc_script.py every hour

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clean environment and upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y numpy pandas || true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade numpy pandas
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute fomc_script.py
        env:
          FOMC_URL: ${{ secrets.FOMC_URL }}
          FOMC_FILENAME: ${{ secrets.FOMC_FILENAME }}
        run: python scrape_logic/fomc_script.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add -f data_upload/fomc_meeting_times.csv
          git commit -m "Update FOMC meeting times CSV file [skip ci]" || echo "No changes to commit"
          git push --force
